export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function DashboardLayout({
  children,
  users,
  notification,
  revenue,
  Login,
}: {
  children: React.ReactNode;
  notification: React.ReactNode;
  users: React.ReactNode;
  revenue: React.ReactNode;
  Login: React.ReactNode;
}) {
  const isLogedin = false;
  return (
    <section>
      {children}
      {isLogedin ? (
        <div style={{ display: "flex" }}>
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              position: "relative",
            }}
          >
            <div>{users}</div>
            <div>{revenue}</div>
          </div>
          <div style={{ display: "flex" }}>{notification}</div>
        </div>
      ) : (
        Login
      )}
    </section>
  );
}
